package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Gamer gamer

swagger:model Gamer
*/
type Gamer struct {

	/* 对阵人的图片, url或者相对路径
	 */
	Logo string `json:"logo,omitempty"`

	/* 对阵人名称, 如 热火、骑士、勇士
	 */
	Name string `json:"name,omitempty"`

	/* 对阵人id
	 */
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this gamer
func (m *Gamer) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
