package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*League league

swagger:model League
*/
type League struct {

	/* League desc
	 */
	Desc string `json:"desc,omitempty"`

	/* League logo, maybe a url, maybe a file path
	 */
	Logo string `json:"logo,omitempty"`

	/* League name, such as NBA, 西甲, 英超
	 */
	Name string `json:"name,omitempty"`

	/* identity of League
	 */
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this league
func (m *League) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
