package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Season season

swagger:model Season
*/
type Season struct {

	/* 赛季属于哪个联赛, 此处为联赛uuid
	 */
	Luuid string `json:"luuid,omitempty"`

	/* 赛季名称,如 2016NBA季前赛
	 */
	Name string `json:"name,omitempty"`

	/* 赛季标识
	 */
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this season
func (m *Season) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
