package game

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteGameByUUIDParams creates a new DeleteGameByUUIDParams object
// with the default values initialized.
func NewDeleteGameByUUIDParams() DeleteGameByUUIDParams {
	var ()
	return DeleteGameByUUIDParams{}
}

// DeleteGameByUUIDParams contains all the bound params for the delete game by UUID operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteGameByUUID
type DeleteGameByUUIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*比赛标识id
	  Required: true
	  In: path
	*/
	UUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteGameByUUIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rUUID, rhkUUID, _ := route.Params.GetOK("UUID")
	if err := o.bindUUID(rUUID, rhkUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteGameByUUIDParams) bindUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.UUID = raw

	return nil
}
