package league

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mintzhao/jili/golang/models"
)

/*GetLeaguesOK 联赛列表

swagger:response getLeaguesOK
*/
type GetLeaguesOK struct {

	// In: body
	Payload []*models.League `json:"body,omitempty"`
}

// NewGetLeaguesOK creates GetLeaguesOK with default headers values
func NewGetLeaguesOK() *GetLeaguesOK {
	return &GetLeaguesOK{}
}

// WithPayload adds the payload to the get leagues o k response
func (o *GetLeaguesOK) WithPayload(payload []*models.League) *GetLeaguesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get leagues o k response
func (o *GetLeaguesOK) SetPayload(payload []*models.League) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLeaguesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetLeaguesDefault Unexpected error

swagger:response getLeaguesDefault
*/
type GetLeaguesDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLeaguesDefault creates GetLeaguesDefault with default headers values
func NewGetLeaguesDefault(code int) *GetLeaguesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLeaguesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get leagues default response
func (o *GetLeaguesDefault) WithStatusCode(code int) *GetLeaguesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get leagues default response
func (o *GetLeaguesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get leagues default response
func (o *GetLeaguesDefault) WithPayload(payload *models.Error) *GetLeaguesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get leagues default response
func (o *GetLeaguesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLeaguesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
