package league

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/mintzhao/jili/golang/models"
)

// NewPutLeagueByUUIDParams creates a new PutLeagueByUUIDParams object
// with the default values initialized.
func NewPutLeagueByUUIDParams() PutLeagueByUUIDParams {
	var ()
	return PutLeagueByUUIDParams{}
}

// PutLeagueByUUIDParams contains all the bound params for the put league by UUID operation
// typically these are obtained from a http.Request
//
// swagger:parameters putLeagueByUUID
type PutLeagueByUUIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*League identity
	  Required: true
	  In: path
	*/
	UUID string
	/*整个联赛信息
	  Required: true
	  In: body
	*/
	League *models.League
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PutLeagueByUUIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rUUID, rhkUUID, _ := route.Params.GetOK("UUID")
	if err := o.bindUUID(rUUID, rhkUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.League
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("league", "body"))
			} else {
				res = append(res, errors.NewParseError("league", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.League = &body
			}
		}

	} else {
		res = append(res, errors.Required("league", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutLeagueByUUIDParams) bindUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.UUID = raw

	return nil
}
